### ISSUE TITLE
Visual mode scroll issue when selection is taller than screen in Xcode

### ISSUE THREAD

**Issue by jannis-baum** [godbout/kindaVim.docs#108]
I have only been able to reproduce this issue in Xcode. When the selection in visual or visual line mode becomes taller than the screen area while expanding it to the top, there is a glitch that keeps scrolling back down to where the selection originally started. See the screen recording below for a demo.

https://user-images.githubusercontent.com/85999315/182609286-d0f6807e-865d-4abf-9b45-b0361da42673.mov

**Comment by godbout** [comment]
yes, i'm aware. unfortunately nothing we can do. the reason is that kV needs to calculate and send the range (area) of visible characters that should be seen on the screen (https://developer.apple.com/documentation/applicationservices/kaxvisiblecharacterrangeattribute#). but Xcode is not responding to that. they're most probably overriding in order to have their own custom behavior.

there's a way to mitigate that tho, although not ideal. you can enforce the `Keyboard Strategy` temporarily by pressing `fn` (like i said, not ideal). that will make kV bypass the Accessibility, and send key remapping instead. if you use key remapping, then the system works as usual. only Apple can do that. see below.

https://user-images.githubusercontent.com/121373/182624845-cde903dc-31a6-4996-b76f-08968c8dffb5.mp4

**Comment by godbout** [comment]
as you saw, in apps that behave "normally", it works:

https://user-images.githubusercontent.com/121373/182626291-7da1f270-d9e1-4602-ae5c-14d61bb50717.mp4

**Comment by godbout** [comment]
all issues reported to Apple, some made public:
* here: https://github.com/feedback-assistant/reports/issues/315
* and here: https://github.com/feedback-assistant/reports/issues/319

now it's up to them. but fyi, in two years of reporting hundreds of issues, not of them have been solved.

**Comment by jannis-baum** [comment]
Thanks for the detailed explanation!

Can you detect that setting the visible character range isn't supported or does it just not do anything? If you can, maybe you could consider automatically falling back to key remapping like `fn` does? If not I think it might be helpful to add a note on this in The Wizard so people like me don't open issues about it🙈

If you don't think either of these would be a good idea, feel free to close this issue as *not planned*, sounds like Apple isn't about to fix this

**Comment by godbout** [comment]
from all the AX APIs kV needs to use to do its job, the visible character range is the least reliable. as far as i recall, i'm just sending the proper data, and the API says it succeeded (which it probably did), then it's the app itself that is doing its own overriding thing. no way to know. i mean you could again ping the range again and compare with before, maybe? etc. bad hacks. no reliable. i have a similar issue with the Electron apps. the AX APIs say that everything went fine, while the Electron apps do shit with the data i send. so for example when i ask to delete something and the API says 👌️ but actually it's not deleted, i could call another API and compare whether the text is different before and after the AX API call asking to delete. but there are many cases in Vim where you actually can't delete. so it's not reliable. i tried. i did some looping etc. for Electron apps. that would slow down kV overall. etc etc etc. best solution i've found so far is the Families, and The Wizard. i think that's just the nature of the kV project itself. which explains why no one even really bothered before. you have to be a little masochist... and mentally disturbed. i think.

**Comment by godbout** [comment]
> If not I think it might be helpful to add a note on this in The Wizard so people like me don't open issues about it🙈

good idea. maybe i didn't do it because there's not that much place. don't wanna write a novel there. also it's quite a special case. no one mentioned before, no one probably noticed either. but i'll see if i can add something, thanks.

i'll check again the browsers thing too. i think for the browsers it's mentioned, and the `Key Mapping` Family is one of the suggestions for that reason.

**Comment by jannis-baum** [comment]
Well I guess I'll add an `fn` key to my keyboard then ^^

> don't wanna write a novel there. also it's quite a special case. no one mentioned before, no one probably noticed either. but i'll see if i can add something, thanks.

Yes, I get not wanting to add minor details there. Now that there is this issue maybe whoever else might notice this in the future won't need to ask anymore, so it might be fine as it is!

From my side this issue can be closed as not planned thanks to your explanations!

**Comment by godbout** [comment]
> Well I guess I'll add an `fn` key to my keyboard then ^^

i know, not super ideal. but i can't think of a better solution for now. and tbh you kinda get used to it. the little pinky for the few times you need it, which shouldn't happen often.

there's actually also other places where you can use that. for example if you're in a TextArea where kV can use the Accessibility Strategy, `CTRL-D` will calculate the new caret location. now if you're in a TextField, that is only one line, calculating the new caret location makes no sense. so what kV does instead, is switching to the Keyboard Strategy, and sending something like `fn left` to macOS (may be something else, don't remember). then if you're in Safari for example, the page will scroll!!!

now what about you **are** actually in a TextArea and you want to scroll the page rather than moving the caret location? well you can do `CTRL-D` and add `fn` and voilà. magic.

the reason it's not _advertised_ yet is that it's still a little funky, and inconsistent. usually what happens is if someone reads this at the beginning, they don't understand anything and find kV complicated (which is kinda fair). but once you're used to it, understand the `Families` thing, why, the Accessibility Strategy vs Keyboard Strategy, then it clicks.

i'm planning to improve this and to advertise it later, but i'm able to find improvements only by using it. so it's taking a bit of time. (and it's not super priority.)

> Yes, I get not wanting to add minor details there. Now that there is this issue maybe whoever else might notice this in the future won't need to ask anymore, so it might be fine as it is!

tbh i'm expecting questions. i want kV to be as straightforward as possible, but the nature of the project itself doesn't allow that. so i don't mind the questions at all. and once a question comes back several time, then i know it's time to add some info somewhere.

that being said, i'll still have a look at the Xcode desc and see if i can add something in there.

> From my side this issue can be closed as not planned thanks to your explanations!

yep. thanks for asking. very thoughtful questions. makes me think, and ultimately will make kV better. thank you!

**Comment by godbout** [comment]
ok, gonna close this one for now. can't find what to add to the Xcode description for now without making the whole thing confusing. i'll see when/if other people keep mentioning the issue.
