### ISSUE TITLE
I did not receive my subscription

### ISSUE THREAD

**Issue by cj** [godbout/kindaVim.docs#110]
Hi,

I signed up for a subscription but did not receive an activation email.

**Comment by godbout** [comment]
😲️

that's a bad one, sorry about that. never happened till now. Paddle is the one sending those emails. you should have received at least two, one is the receipt, one is the License code.

so i'm gonna do three things now:
1. force the resend of those emails through Paddle
2. when you want to recover your License you can go through kindaVim, that sends you to an online page where you can get an email back with your License: https://kindavim.app/recover of course you can't do that because you haven't received your email with your Order Numbers. so i'm gonna do that for you. that email is sent by my own servers
3. i'm gonna send an email to Paddle and scold them vehemently

sorry again! that's not super cool.

**Comment by cj** [comment]
Thank you!
