### ISSUE TITLE
Incorrect paste insertion

### ISSUE THREAD

**Issue by bromanko** [godbout/kindaVim.docs#113]
When pasting in normal mode, the contents are placed at the end of the sentence rather than after the current character. See this video.

https://user-images.githubusercontent.com/160158/183939651-40cb03d1-1df9-4df7-8bbf-09e3ed49a328.mov

**Comment by godbout** [comment]
the Vim register system is more complicated than it appears. actually most of Vim is more complicated. it feels like magic but there's a lot of stuff happening behind the scenes. i'm not talking about kV, i'm talking about Vim in general.

when you copy text, there's two _types_ of copying, depending on the motion you used: `Characterwise` and `Linewise`. a `dd` will copy the deleted text `Linewise`, `ciw` will copy the deleted text `Characterwise`. this has an important implication on how the text is going to be pasted afterwards. a text that has been copied `Linewise` will be pasted on a new line. this is the case that you are experiencing. a text that was been copied `Characterwise` will be pasted at the current position (with `p`). kV follows the exact same behavior as Vim on this (if not, that's a bug).

video incoming...

**Comment by godbout** [comment]
https://user-images.githubusercontent.com/121373/183942588-8ce21f72-6d5d-43ca-b449-88c4716d39e8.mp4

yes, Viming is hard 😁️ (and that's one of the reason why kV is a sub! massive continuous work and research.)

**Comment by godbout** [comment]
for more info, from the Vim doc: http://vimdoc.sourceforge.net/htmldoc/change.html#linewise-register

```
If the command that was used to get the text into the [register](http://vimdoc.sourceforge.net/htmldoc/sponsor.html#register) was |[linewise](http://vimdoc.sourceforge.net/htmldoc/motion.html#linewise)|,
Vim inserts the text below ("p") or above ("P") the line where the cursor is.
Otherwise Vim inserts the text after ("p") or before ("P") the cursor.
```

**Comment by bromanko** [comment]
Thanks for sharing all the detail! You are right. I compared with Emacs and thought it was behaving differently but now I can't reproduce that. If I see any inconsistency I'll re-open this.

For what it's worth, the copy came from outside of kindaVim. It was in the macOS pasteboard.

**Comment by godbout** [comment]
> For what it's worth, the copy came from outside of kindaVim. It was in the macOS pasteboard.

@bromanko yeah so currently at least kV doesn't keep any internal register and it uses the macOS pasteboard instead. the thing is, it doesn't really matter what's in the pasteboard. what matters is how you lastly yanked with kV. the style of yanking (`Linewise` or `Characterwise`) is applied when the pasting happens (may need to add a leading linefeed, may need to remove a leading linefeed, etc.). so in your case what happened is that you yanked with a `Linewise` move, then did you something else on macOS, copied something, then pasted that thing with kV. kV checked the last yank style, it was `Linewise`, so that's what it applied.

that's the current state of affairs. let me know if you think this should be handled better, and how. i guess i could "detect" that something was added to the pasteboard out of kV but then? force `Characterwise`? why? i can't really think quickly of a better solution for now.  (multiple registers is planned but way way down the list.)

**Comment by godbout** [comment]
just for the fun of it, and for my own reminder, there's also even motions that may copy `Characterwise` or `Linewise` depending on the context. for example `cib` would copy `Characterwise` most of the time, but for some cases (complicated rules) it will copy `Linewise`, like if an opening block is followed by a linefeed, or a closing block is preceded by a linefeed or linefeed + only blanks, etc, etc...
