### ISSUE TITLE
Visual Select Paragraph

### ISSUE THREAD

**Issue by keithadams** [godbout/kindaVim.docs#114]
I'd like to use `(` and `)` with visual mode to select blocks of text.

For example, typing `(V)` in normal mode selects a block of text regardless of where your cursor is in the block.

Thanks!

**Comment by godbout** [comment]
yes, `(` and `)` are not implemented for Visual Mode. will add, thanks.

question tho, any reason why you don't use `ip`? it should be done for what you need. visually grabbing inner paragraphs:

https://user-images.githubusercontent.com/121373/184793513-df6c8495-b7fe-47e4-9377-c7f330edbc76.mp4

**Comment by keithadams** [comment]
>question tho, any reason why you don't use ip?

I have my left/right shift keys mapped to parentheses on tap and I am used to using them to move around as well as select things. That said, I should probably use `vip` and `vap` more.

>it should be done for what you need. visually grabbing inner paragraphs

Awesome. I tried `vap` but I didn't try `vip` for whatever reason. I'll use that.

**Comment by godbout** [comment]
> I have my left/right shift keys mapped to parentheses on tap and I am used to using them to move around as well as select things. That said, I should probably use `vip` and `vap` more.

👌️

> Awesome. I tried `vap` but I didn't try `vip` for whatever reason. I'll use that.

you can always check the list of what's currently implemented here (for the Accessibility Strategy): https://github.com/godbout/kindaVim.docs/blob/master/AccessibilityStrategyImplementation.md#accessibility-strategy

if it's not implemented you can request. if it's implemented but doesn't behave properly then it's a bug to be reported :p

i prioritize what i'm using first (hehe) or what people are asking, because working on a move takes quite some work, even more Visual ones. (which is why `vap` is not there... yet.) but if it's requested i would usually add them.

**Comment by godbout** [comment]
i'm working on `(``)` now and just wanted to precise that those are not paragraph delimiters, but sentences. so depending on where you use it, you may not get the results you're expecting. in `Visual Mode Characterwise` the move will stop at sentences. for `Visual Mode Linewise` it'll stop at paragraphs.

also in the example you're giving you're using `V` not `v`, so that would indeed go with the paragraph.

anyways, just me trying to show you that you're doing it wrong. 

HHAHHAHAHAHAHAHHAHAAH

**Comment by godbout** [comment]
ok, another thing. regarding using `(``)` while you're in Visual Mode **Linewise**. usually i don't allow those moves, because we can't do them with the macOS APIs and the macOS selection system. so i'm not sure how you see this working?

for example, see below how basically 1) i use `(` to go the the beginning of the previous **sentence**, then i use `V` to enter Visual Mode Linewise to grab the **whole file line**, then using `)` or `(` is moving the caret within the selected line. this is not doable with the macOS buffer (Vim uses its own buffer). 

https://user-images.githubusercontent.com/121373/187068642-6e5c7018-4f47-4117-973a-7adb7aa57bd1.mp4

so what i do is i just don't do anything when using those kind of moves in **Linewise** mode. this is the case of `W/w`, `B/b` etc. i think the same should apply for `(` and `)`.

**Comment by godbout** [comment]
> so as said, this for `Visual Mode Characterwise`. not for `Linewise`

i'm gonna add some sort of `Linewise` for `(` `)`. we can't really do exactly what Vim does, because the macOS selection system doesn't allow it, but i'll still add something.

**Comment by godbout** [comment]
also `a paragraph` type of moves coming in kV36.

**Comment by godbout** [comment]
added something for Visual Mode Linewise and `(` `)` in kV37: https://github.com/godbout/kindaVim.docs/releases/tag/37

closing.
