### ISSUE TITLE
Add Visual mode `i'`, `i"`, i`

### ISSUE THREAD

**Issue by jannis-baum** [godbout/kindaVim.docs#115]

**Comment by godbout** [comment]
i'm splitting this in two (other part here: #116). the reason again is because that requires two whole set of investigation/tests/implementations. for `iB` (and co.) and `aB` it was slightly different as `aB` is just `iB` including the opening and closing blocks. but that's not the case of the quotes. `i"` grabs what within the quotes, while `a"` may grab trailing spaces, or leading spaces, or none, etc.

usually even for `iB`/`aB` i would internally split, but it was not too much work from one to the other. for the quotes it's gonna be too different things. i'll do `i"` first, release, and then `a"`.

**Comment by godbout** [comment]
@jannis-baum just a thought. i'm gonna stick with Vim's behavior again, although i've been wondering sometimes if i should "adapt" kV rather than just copying the Vim moves. 

for example for Visual Mode `i"`, the behaviors are different depending on the position of `head` and `anchor` of the selection:

https://user-images.githubusercontent.com/121373/185761471-067c2513-36e2-4922-b6ae-50759adabce6.mp4

but in Vim you can see where are the `head` and the `anchor`. in kV, you can't (at least for now). so the same behavior may be a bit harder to understand, or track.

on the one hand i feel like somehow it'd be smart to "adapt", on another hand why would i change the original behavior, that may—or should—be what most people except?

any thoughts on this? can i borrow your brain a bit still? :D

**Comment by jannis-baum** [comment]
Interesting issue! I'm not sure what the best way to go would be without being able to distinguish head & anchor... I can see pros and cons of both sticking with Vim as well as just having it select the nearest possible range. Either way I honestly have never though about the exact behavior of this move before and I'm sure most other people haven't either🙈

Different thought though, since the core issue seems to be that the head isn't visible:

Would it be feasible to make the head visible by having the selection flash back and forth? Let's say I have a selection with `H` being the head in Vim, `A` being the anchor and `-` being some part in between. So a selection

```
some text
A---H
```

in kV will currently just look like

```
some text
-----
```

i.e. we can't know where the head is. What if instead it would flash back and forth between that and

```
some text
----
```

meaning it blinks where the head is? I of course have no idea how much this would interfere with the current architecture but if I may take a careful guess it shouldn't sound all too horrible to add a timer and add and subtract one character from the selected range? If we had this, it would make it easier to stick with original Vim behavior for your original question.

---

Getting off topic here, but maybe this could also be cool for Normal mode as another way to distinguish it from a one-character-selection. I actually have my Vim set up like this as well: while I move the cursor it's just this "one-character-selection", but as soon as I stop moving it for a short amount of time it starts blinking in place, similar to the normal macOS typing cursor's blinking behavior.

What do you think?

**Comment by godbout** [comment]
> Either way I honestly have never though about the exact behavior of this move before and I'm sure most other people haven't either🙈

yeah. same for me. and same for the previous Visual Mode `ib` etc. it's more complicated than we think at first. but somehow i need to investigate, and make choices. for those complicated moves i felt a few times that i could "simplify" and maybe provide a more "natural" way? like the Visual Mode `i"`. wherever the position of the `head` and `anchor` relative to each other, i could make the move happen. in Vim, most of the time, if the `head` is before the `anchor`, the move _bips_. (but not in all cases...)

but probably ultimately it's better for me to stick to Vim. because that means less support. (probably everyone will want their own custom moves.)

> Would it be feasible to make the head visible by having the selection flash back and forth? 
> What do you think?

yeah, i think a nice blinking cursor will be needed, and would nice, at a later stage. adding/subtracting from the selected range is tricky, because this is used by the AX Engine at each move to calculate the positions. i guess it's feasible, but that would require keeping track of several things, and sync them properly, even with the timer. add complexity, and easy to break i think. another way could be to grab the background surrounding screen color, and to overlay that on top of the selection. that may look like blinking, but in itself the selection doesn't change, which wouldn't require any change in the Engines. but that's still a big piece that requires a lot of research and experimentation. so it's gonna be for later. at least after the VM `i"` and co, and the beginning of the `.` motion.

**Comment by godbout** [comment]
ah fuck this is even more complicated than i thought lol i wanna die

https://user-images.githubusercontent.com/121373/186069391-8523e390-b917-4038-85e7-6dac22ab4deb.mp4

depending on the position of the `head` in relation to the `anchor` it goes select different parts if there's multiple `quotedString` available 😭️

**Comment by godbout** [comment]
i think that to solve this it's gonna be time to switch to heave regex, which would also solve #6.

but i'm gonna release a simple version first. so that we get `i"` and `a"` (and co.) usable in like 90% of the use cases.

**Comment by godbout** [comment]
added in kV34: https://github.com/godbout/kindaVim.docs/releases/tag/34

it's the worst implementation i've made of a motion. way too complicated. it's gonna fit my personal needs for now. see how you feel about it, and please report if there's cases that you use and that are wrong, and i'll patch.

**Comment by godbout** [comment]
added `a"` and co. too. i'm dead 😂️
#116

**Comment by godbout** [comment]
btw there's still some weirdness that i'm discovering while using and that i'll iron out (like if there's nothing between two quotes). i'll patch little by little, but please feel free to report yours!

**Comment by godbout** [comment]
kV35 out: https://github.com/godbout/kindaVim.docs/releases/tag/35
fixes the few issues with the moves. as far as i'm concerned this can be closed.
