### ISSUE TITLE
add Todoist

### ISSUE THREAD

**Issue by JoharyNyAina** [godbout/kindaVim.docs#118]

**Comment by godbout** [comment]
will do. thanks.

**Comment by godbout** [comment]
currently, you can add it manually to the `Electron` Family, or the `Key Mapping` Family, depending on the fields where you want to use kV. some fields will work very well with `Electron`, some will not work at all (because Todoist is using StaticText Elements rather than TextFields or TextAreas). if you want it to work kinda ok in all fields, add it to the `Key Mapping` Family, but not text calculation can be done there, so it's all done by key remapping. up to you. depending on how you use Todoist, and which Vim moves you need.

**Comment by godbout** [comment]
added in kV34: https://github.com/godbout/kindaVim.docs/releases/tag/34
