### ISSUE TITLE
Use 'jk' AND 'kj' and use it to activate AND deactivate normal mode

### ISSUE THREAD

**Issue by januz** [godbout/kindaVim.docs#125]
Hi, I heard about kindaVim for the first time today and am pleasantly surprised from my first tests.

Two things I wondered were

- would it be possible to define both 'jk' and 'kj' as sequence to start normal mode (that's what I have in VIM as well as it allows me to just punch the keys without having to be cautious about hitting 'j' first)?
- maybe this is just me not understanding the application yet but if I understand correctly only 'i' (or return in some instances) ends normal mode. I was expecting to be able to hit 'jk' again to leave normal mode or to hit 'esc'. Would that be possible to implement?

Thanks so much!

**Comment by godbout** [comment]
> Hi

hello!

> would it be possible to define both 'jk' and 'kj' as sequence to start normal mode (that's what I have in VIM as well as it allows me to just punch the keys without having to be cautious about hitting 'j' first)?

not in kV itself. in the Preferences you can choose whether you enter with `escape`, a sequence of two characters, or a custom keyboard shortcut. but you can't have two sequences. i'm most probably never gonna add this into kV because 1) then people may need three or more, so you need a whole custom system set up 2) that whole custom system set up is actually the goal of a lot of tools like Karabiner-Elements, Hammerspoon, BetterTouchTool, Keyboard Maestro, etc. do you know a bit about those tools? with Hammerspoon you could easily set up your `kj` sequence (and even add some more like `jj` or `kk`) to remap to the `jk` you set up in kV. then they would all work. let me know if you need some help with this.

> maybe this is just me not understanding the application yet but if I understand correctly only 'i' (or return in some instances) ends normal mode. I was expecting to be able to hit 'jk' again to leave normal mode or to hit 'esc'. Would that be possible to implement?

this has been discussed here and there yeah, and i had several good reasons, although i can't remember all of them now 😅️ but in Vim itself you can only go back to `Insert Mode` with the following motions: `.A, .a, .C, .c, .I, .i, .O, .o, .S, .s`. my goal with kV is to stick as much as possible to Vim's habits. that was the whole point from the start. all those hard learned muscle memory built, you can use them everywhere. if kV is too different from Vim, going back and forth is gonna cause trouble, and i want to avoid this.

some places where this has been discussed:
* https://github.com/godbout/kindaVim.docs/issues/107#issuecomment-1204021072
* https://github.com/godbout/kindaVim.docs/issues/36#issuecomment-1011128987

might be worth reading those comments/threads.

but this is of course discussable. so let me know what you think once you've digested the answers.

**Comment by godbout** [comment]
somehow related to the `jk` `kj` thing, you can remap keys on a per Vim mode basis: https://github.com/godbout/kindaVim.docs/discussions/117

the `kj` mapping to `jk` would use the same tools. (only Hammerspoon needed even.)

**Comment by januz** [comment]
Thanks for getting back to me with suggestions (I will look into setting up `kj` to `jk` mapping in Karabiner-Elements) and the explanation for why you don't allow leaving normal mode by hitting `jk` or `esc`. I agree with the rationale in the text editing context but I often use kV for scrolling lists with VIM keys and in that context it would feel more natural to just hit `jk` or `esc` to leave the mode and hitting `i` etc. feels somewhat unnatural. Thanks!

**Comment by godbout** [comment]
> (I will look into setting up `kj` to `jk` mapping in Karabiner-Elements)

actually KE is a better choice for remapping keys to enter Normal Mode yes, as KE is a very low level keyboard remapper (driver), so it's always remapping before any other app.

> I agree with the rationale in the text editing context but I often use kV for scrolling lists with VIM keys and in that context it would feel more natural to just hit `jk` or `esc` to leave the mode and hitting `i` etc. feels somewhat unnatural. Thanks!

i understand, but that's a little too specific i think for me to handle in kV. my thoughts:
1. first, `escape`. when you're in Visual Mode, what should `escape` do? go back to `Normal Mode` or go back to macOS then? probably you want it like in Vim, which means going back to `Normal Mode`. so you'd want `escape` to go back to macOS but **ONLY** when in `Normal Mode`. so sometimes the behavior follows Vim, sometimes it doesn't. up to someone's taste. too specific for me to cement this within kV.
2. second, `jk` to leave back to macOS. people asked also that their custom shortcut exits back to macOS. now people enter `Normal Mode` with `control D`. well guess what, `control D` is a Vim motion. so when they're in `Normal Mode` and press `control D`, what should it do?! the Vim motion, or leave to macOS. well, "it depends". so yeah, but no. i guess for the sequence that _could_ be done, but again, at least to me, that's confusing. in some case you can use the same way to exit, but in some case no? while there is an official list of motions that are about exiting `Normal Mode`, when in Vim, Neovim, Vi, etc.

maybe there's something to do with KE/hs? i'd think you could remap `jk` and `kj` to `escape` with Hammerspoon, and use `escape` to enter `Normal Mode`. then you'll be able to use `escape` to exit `Normal Mode`. that's a special case because you need to be able to send back `escape` to macOS when you chose to use `escape` to enter `Normal Mode`. although if you do this, you `escape` key will always be bound to enter `Normal Mode`, even if you use `jk`/`kj`.

another way is to allow for the `command` passthrough, and use `command escape` instead of just `escape`:

![Screenshot 2022-09-14 at 00 18 50](https://user-images.githubusercontent.com/121373/189954310-497ee136-3bf1-4594-9d29-3aaf39d931c1.png)

**Comment by januz** [comment]
Thanks for the added input @godbout! I was thinking that I might be able to use the procedure that was described in the link you sent to remap `jk`/`kj` in KE in a state-dependent manner, i.e., if there is no kV state, `jk`/`kj` activates Normal mode. If Normal mode is active, `jk`/`kj` map to `i` to exit Normal mode, etc. Let's see what I can come up with. Definitely understand that you do not want to build in too much flexibility here!

**Comment by godbout** [comment]
> Thanks for the added input @godbout!

sure no worries. i understand that as a newcomer kV may not be what you expect, but i'll try to explain as much as i can (and remember) why things are the way they are. there is usually a good deal of research, investigation and pondering before every decision i made for kV :))

> I was thinking that I might be able to use the procedure that was described in the link you sent to remap `jk`/`kj` in KE in a state-dependent manner, i.e., if there is no kV state, `jk`/`kj` activates Normal mode. If Normal mode is active, `jk`/`kj` map to `i` to exit Normal mode, etc. Let's see what I can come up with.

that definitely sounds doable and that would also definitely seem to be doing what you're looking for.

> Definitely understand that you do not want to build in too much flexibility here!

yeah as you can imagine a lot of people want a lot of different flavors. so what i want to do with kV is sticking to Vim's behavior as much as possible, except for when it's not possible or it really does make sense to integrate with macOS. for the rest, building some sorts of bridging (like you saw in the link shared above) to hook other tools seem to me the right way to go. probably later we'll get some cookbooks etc.

in any case, let me know how it goes! and feel free to share what you came up with in the `Discussions`, might help some others.

**Comment by godbout** [comment]
> actually KE is a better choice for remapping keys to enter Normal Mode yes, as KE is a very low level keyboard remapper (driver), so it's always remapping before any other app.

just an update on that. i'm working now to get kV working properly with key remappers that use the event tap system, like Hyperkey and Hammerspoon (see https://github.com/godbout/kindaVim.docs/issues/104).

once this is done (most probably in kV38), you'll be able to use only Hammerspoon if you wish in order to remap keys to enter `Normal Mode`, with just a couple lines of code.

**Comment by januz** [comment]
Thanks, @godbout! I actually got it to run in the following way:

- set kV states using Hammerspoon as described in the [issue](https://github.com/godbout/kindaVim.docs/discussions/117) you sent earlier in this thread
- set kV's activation to a custom shortcut in Hyperkey style: 
    <img width="450" alt="Screen Shot 2022-09-15 at 07 34 27" src="https://user-images.githubusercontent.com/1440498/190431922-d17ebb28-3b6f-4a3d-a4b6-713b46834283.png">
- set Karabiner Elements (configured through `goku`) up to use `jk/kj` to start Normal mode (if kV state is not Normal mode) and use `jk/kj` to exit Normal mode (if kV state is Normal mode)

```
  {
   :des "simultaneous jk/kj press to enter kindaVim normal mode"
   :rules [
           [
            [:j :k] :!!equal_sign
            ["kVNormal" 0]
           ]
          ]
  }
  {
   :des "simultaneous jk/kj to exit kindaVim normal mode"
   :rules [
           [
            [:j :k] :i
            ["kVNormal" 1]
           ]
          ]
  }
```

**Comment by godbout** [comment]
🙌️🙌️🙌️

**Comment by godbout** [comment]
can we close? but i'll write something in the `Discussions`, summarizing what you did.

**Comment by januz** [comment]
@godbout After a few months of trying (the basic setup as described above works but there are issues with excluding applications, etc.) I went back to just use KindaVim's functionality to specify a two letter key combination to activate KindaVim. This works way better because I can exclude applications directly in KindaVim, KindaVim still works in Alfred if the frontmost application is an excluded one, etc.

But I'm back to square one / where we started with this issue: most of the time I'm getting it right, but I end up typing "kj" frequently over the course of the day and end up swearing :)

I know that you weren't really enthused about the request to be able to specify 2 different activating methods because you worry that this might lead to more and more requests of that kind. Is there any way that I can convince you? One possible middle ground might be that two-letter combinations always work in both directions (i.e., when I specify "jk", both "jk" or "kj" will activate) or to provide a checkbox for two-letter combinations that let's the user choose whether they want the combination to only work in the specified order or also the reverse order. Then it would not really be "specifying 2 options to activate" but a modifier that only applies to two-letter combinations.

Let me know what you think. This would be fantastic for me personally but I somewhat assume that most people who use "jk" to activate normal mode in VIM typically also specify "kj", i.e., their muscle memory is just "hammer quickly on these two keys" not a given sequence.

Thanks so much!

**Comment by godbout** [comment]
ok, i will have to contact GitHub and ask them to remove that feature of being able to reopen issues...

😂️😂️😂️

> @godbout After a few months of trying (the basic setup as described above works but there are issues with excluding applications, etc.) I went back to just use KindaVim's functionality to specify a two letter key combination to activate KindaVim. This works way better because I can exclude applications directly in KindaVim, KindaVim still works in Alfred if the frontmost application is an excluded one, etc.

but at least with Hammerspoon and Karabiner-Elements you can precise on which app your settings take precedence. are you aware of that?

> 
> But I'm back to square one / where we started with this issue: most of the time I'm getting it right, but I end up typing "kj" frequently over the course of the day and end up swearing :)

according to "latest studies", swearing is good 😂️😂️😂️

> I know that you weren't really enthused about the request to be able to specify 2 different activating methods because you worry that this might lead to more and more requests of that kind. Is there any way that I can convince you? One possible middle ground might be that two-letter combinations always work in both directions (i.e., when I specify "jk", both "jk" or "kj" will activate) or to provide a checkbox for two-letter combinations that let's the user choose whether they want the combination to only work in the specified order or also the reverse order. Then it would not really be "specifying 2 options to activate" but a modifier that only applies to two-letter combinations.
> 
> Let me know what you think. This would be fantastic for me personally but I somewhat assume that most people who use "jk" to activate normal mode in VIM typically also specify "kj", i.e., their muscle memory is just "hammer quickly on these two keys" not a given sequence.
> 
> Thanks so much!

yeah people been requesting custom mapping etc. but that's a crazy amount of work. so crazy that **THERE ARE APPS JUST FOR THAT**. with their own set of problems, bugs, etc. it's crazy work. what i'm thinking now (on the top of my head) would be maybe adding a "dyslexic" option yeah, especially for you, that would allow for the sequence in any order (well, two orders really). that could work i think.

**Comment by januz** [comment]
>  ok, i will have to contact GitHub and ask them to remove that feature of being able to reopen issues...

:) 

> at least with Hammerspoon and Karabiner-Elements you can precise on which app your settings take precedence. are you aware of that?

Yes, in a standard setting that works well. In this specific instance where I had to combine a variable with an application condition it didn't.

> what i'm thinking now (on the top of my head) would be maybe adding a "dyslexic" option yeah, especially for you, that would allow for the sequence in any order (well, two orders really). that could work i think. edit: and honestly i like because of the name of the option: "dyslexic" 😂️ sounds like making fun of users. very good.

Hehe, I'll take the insult if you give me the feature. Thanks so much!

**Comment by godbout** [comment]
alright. added to the TODO. will investigate. i hope to get an answer in the next few weeks.

**Comment by godbout** [comment]
proof of concept done:

https://github.com/godbout/kindaVim.docs/assets/121373/66f3e453-e81a-4908-89c9-101e02911346

now it's gonna be about getting this automatedly tested, writing proper clean code, and finding a nice UI for the Settings. then it'll be available probably for kV55.

**Comment by januz** [comment]
Great, thank you!!

**Comment by godbout** [comment]
added in kV55: https://github.com/godbout/kindaVim.docs/releases/tag/55

**Comment by januz** [comment]
Thank you so much @godbout, works great!

**Comment by godbout** [comment]
welcome! hopefully it's gonna be useful to some more people
