### ISSUE TITLE
Dash switching to normal mode changes page

### ISSUE THREAD

**Issue by Husky22** [godbout/kindaVim.docs#127]
At first thanks for making kindaVim! Its a really neat app!

But everytime I press esc to switch to normal mode in Dash.app it goes to the previous page in alphabetic order.
I dont think that is intended.
I have mapped my capslock key to esc - maybe that Information is useful.

**Comment by godbout** [comment]
i used Dash daily and it works fine here. `caps lock` mapped to `escape` also.

1. does kV enter `Normal Mode` at all or just Dash goes to the previous page?
2. any other tool that could take precedence running? Hammerspoon, BTT, Karabiner-Elements, etc.?

**Comment by godbout** [comment]
https://user-images.githubusercontent.com/121373/191262143-ca26f19e-997b-4685-b202-6681f9682c4d.mp4

**Comment by Husky22** [comment]
Yes its possible for me to go into normal mode. 
While I was trying to capture a video for you I realized that somehow everytime I click escape a left button press gets triggered. Ill have a look into that. I am using Karabiner elements maybe the answer lies here! But thanks alot already for your quick response :)

**Comment by godbout** [comment]
> Yes its possible for me to go into normal mode.
> While I was trying to capture a video for you I realized that somehow everytime I click escape a left button press gets triggered. Ill have a look into that. I am using Karabiner elements maybe the answer lies here! But thanks alot already for your quick response :)

my pleasure. yeah, probably best to get rid of the extra left click first. please reopen if at later stage you think this is still a kV issue. enjoy the ride.

**Comment by Husky22** [comment]
Ok it only happens when kV is active. Looking at my keypresses after kV turned off I couldnt see the left click anymore

**Comment by godbout** [comment]
kV doesn't generate any mouse click tho.

1. have you tried quitting Karabiner-Elements?
2. does it happen only with Dash?

there's zero code in kV that generates mouse click, so i would assume that it comes from some other automated tools?

**Comment by godbout** [comment]
also:

1. do you have any tool that remaps some key combinations to a left click?
2. what's your macOS keyboard shortcut to go back to a previous page (especially in Dash)

**Comment by godbout** [comment]
> Sorry I wasnt being clear. It triggers a left arrow button click - not a mouse click.

oh, a _key press_ 😂️
 
> In Dash my keyboard shortcut to go back is the left arrow.

ok, so that's one of the issue.

here's what's happening:

when you enter `Normal Mode` in Vim, the block cursor moves to the previous character. when a text field is not Accessible, kV generates a left key press instead to achieve the same effect. see below:

https://user-images.githubusercontent.com/121373/191287051-053b8f7f-23a5-431b-87e3-1309728cc7ef.mp4

kV detects whether a field is of a text type or not, and only generates a left key press if it's one, else it doesn't.

there's **one** type of field tho that can be both: WebViews. in Mail, the composer is a WebView. but in Safari, a page is a WebView too.

i _think_ i've made an exception that if a WebView is in Safari, a left key shouldn't be generated. Dash is mostly a browser, and i'm pretty sure it's a WebView too. because there's no exception, kV generates a left key press. because your backward is map to a left key press, Dash goes back a page.

i'll check and confirm this, will keep you updated, and will fix. i've never noticed myself because sound is off on my laptop usually, so i never heard the "bip".

**Comment by godbout** [comment]
> i'll check and confirm this, will keep you updated, and will fix. i've never noticed myself because sound is off on my laptop usually, so i never heard the "bip".

confirmed. the exception is not specifically for `Safari`, it's for WebViews that are not web pages (where their AX URL starts with `http`). Dash WebViews return a `dfile` URL. so it's clear where the issue lies. just need to find a proper solution.

**Comment by godbout** [comment]
should be ok now in kV42: https://github.com/godbout/kindaVim.docs/releases/tag/42

if all fine with you, let's close the issue. thanks!

**Comment by Husky22** [comment]
Perfect Thanks alot!
