### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by biye1999** [godbout/kindaVim.docs#128]
I'm from China and the timezone is UTC+8. When it's daytime in my time, App is sleeping.
<img width="511" alt="image" src="https://user-images.githubusercontent.com/62197631/192078762-25c5b318-b531-4a08-8a51-9a478f780bf5.png">
As a fan of fanatical vim,KindaVim is what I dream App.

**Comment by godbout** [comment]
well this is awkward because i'm in China too, and also UTC+8 😅️

so, when you mean the app sleeps during the day:
1. i guess you don't have a License?
2. during which hours kV is sleeping?

it's supposed to be sleeping between 5am and 1pm if you don't have a License. this is auomatedly tested and it's been working fine, but it seems you're on Ventura. so i'll have an extra check on that.

**Comment by godbout** [comment]
no news. closing.
