### ISSUE TITLE
Linewise visual mode does not respect gj/gk mapping

### ISSUE THREAD

**Issue by agbohub** [godbout/kindaVim.docs#133]
Linewise visual mode (`V`) does not appear to follow the user setting of “Map jk to gj gk for Auto, PG-R and Electron Families”.

kindaVim version: 42. Reproducible in Notes.app, Bear.app, etc.

**Comment by godbout** [comment]
this is by design. the main goal (at least at first) of kV is to stick to Vim's behaviors/habits, so that you don't have to cognitively _think_ about how to do something under macOS. there's two types of Lines if Vim: File Lines and Screen Lines. in Vim Visual Mode, `gj`/`gk` select **File Lines**, not Screen Lines. the _caret_ moves by Screen Lines yes, but the selection is over the whole File Line. having a selection AND a caret working independently is a part of Vim that we can't reproduce, just because macOS doesn't work this way: once you select the caret is gone. but as far as i'm concerned, the selection should stick with what Vim does. see below:

https://user-images.githubusercontent.com/121373/194737753-5e10d541-7ce7-462c-8eb1-18a4c89b8bce.mp4

let me know what you think.

**Comment by agbohub** [comment]
> this is by design. the main goal (at least at first) of kV is to stick to Vim's behaviors/habits, so that you don't have to cognitively _think_ about how to do something under macOS. there's two types of Lines if Vim: File Lines and Screen Lines. in Vim Visual Mode, `gj`/`gk` select **File Lines**, not Screen Lines. the _caret_ moves by Screen Lines yes, but the selection is over the whole File Line. having a selection AND a caret working independently is a part of Vim that we can't reproduce, just because macOS doesn't work this way: once you select the caret is gone. but as far as i'm concerned, the selection should stick with what Vim does. see below:
> 
>  ScreenFlow.mp4 
> 
> let me know what you think.

Many thanks for the color! Knowing that it is a feature by design I am happy now to simply use `v$` as a workaround.

**Comment by godbout** [comment]
@agbohub actually `v$` is not gonna work either 😅️ the `$` will go at the end of the `File Line`, not `Screen Line`. what you need to use is `vg$`: https://vimdoc.sourceforge.net/htmldoc/motion.html#g$

see also: https://vi.stackexchange.com/questions/9762/how-to-go-to-the-end-of-the-line-even-in-on-a-wrapped-line

**Comment by agbohub** [comment]
> @agbohub actually `v$` is not gonna work either 😅️ the `$` will go at the end of the `File Line`, not `Screen Line`. what you need to use is `vg$`: https://vimdoc.sourceforge.net/htmldoc/motion.html#g$
> 
> see also: https://vi.stackexchange.com/questions/9762/how-to-go-to-the-end-of-the-line-even-in-on-a-wrapped-line

Tried both `v$` and `vg$` in Notes.app and you are right! Must be another quirkiness of Bear.app 😅.

**Comment by godbout** [comment]
> Tried both `v$` and `vg$` in Notes.app and you are right! Must be another quirkiness of Bear.app 😅.

maybe it depends where you use it in Bear? seems to me like in normal paragraphs `v$` and `vg$` are working as expected 🤔️

**Comment by agbohub** [comment]
> > Tried both `v$` and `vg$` in Notes.app and you are right! Must be another quirkiness of Bear.app 😅.
> 
> maybe it depends where you use it in Bear? seems to me like in normal paragraphs `v$` and `vg$` are working as expected 🤔️

You are right! It is mostly with headings and lists in Bear.

**Comment by godbout** [comment]
ok maybe there's something i don't understand here, but in lists and headings it seems to be that the `$` and `g$` moves are still respected.
