### ISSUE TITLE
Hitting ESC in MacVim dims all other apps

### ISSUE THREAD

**Issue by georgevreilly** [godbout/kindaVim.docs#137]
If I hit `ESC` in MacVim, then all other apps dim, just as if I were using Chrome or Slack. I have dropped the MacVim app onto the Off column in the Wizard, which fixed the behavior. Should a few well-known apps, like MacVim, be Off by default?

**Comment by godbout** [comment]
yeah, it's not just the dimming, it's kV taking over completely. indeed for some apps you'll clearly want kV to back off. and as you've seen, this is done by putting those apps in the `Off` Family.

there's on ongoing discussion about whether putting some apps by default in some Families: https://github.com/godbout/kindaVim.docs/discussions/48

the topic tho was about `built-in` apps, that any macOS has by default, rather than other apps that people may or may not have.

that being said, the rationale behind the current implementation is:
1. users **WILL** have to go through the Families sooner or later. so i think it's good that they know early. it's also good that they learn about it starting by putting apps in the `Off` Family. pretty straightforward.
2. why letting users manually do this while kV has an App Catalog with the information needed? because for some apps, a user may prefer a Family over another one. for example, for some Electron apps, depending on what motions a user uses, he may choose to put an app in the `Electron` Family, or the `Key Mapping` one. this is up to the user to know what he prefers, i can't make the choice for them.

so the best implementation i've found currently is the current one. i prefer giving users less choices. less choices = less overwhelmed. it's my job to research, and see what's better. but in that case, i can't. we still could put some apps by default yes, like MacVim, iTerm, Terminal, etc. but honestly i don't like the fact that for some apps it'll be done automatically, and for some you'll have to do it manually. the lack of consistency would disturb me, even as a user.

let me know your thoughts.

**Comment by godbout** [comment]
closing. please reopen if you think this is still an issue that needs to be discussed. we could also open a discussion rather than a GH issue.
