### ISSUE TITLE
add Hepta.app

### ISSUE THREAD

**Issue by javid-g** [godbout/kindaVim.docs#142]
Would be much appreciated!!

**Comment by godbout** [comment]
@javid-g will do. can you provide a link tho? there seems to be two Hepta apps, one is about books and highlights, one is an accounting app. thanks.

**Comment by javid-g** [comment]
Definitely, it’s https://heptabase.com/. Completely unrelated, but curious if a yearly subscription is something that may be on the horizon?

**Comment by godbout** [comment]
> Definitely, it’s https://heptabase.com/. 

nice. thanks. so that was the third option 😂️
i'll add for the next release.

> Completely unrelated, but curious if a yearly subscription is something that may be on the horizon?

there's two or three people that have been asking. i'm gonna dump below the current state of affairs, the rationale behind the current system, etc. it's just a dump because i'm still digesting, and the outcome is still open:

1. a yearly subscription would be better **FOR ME** in terms of **MONEY**. Paddle takes 5% (or 10? forgot) per transaction, **plus a fixed 0.5$**. which means for each monthly sub i'm paying around $0.75. for a yearly sub i would pay $0.5 for the transaction, rather than $0.5 * 12. that is if the yearly sub is 3.28 * 12, rather than with one or two months of discount. if i give a two months discount, then it's back to the same. again, talking here just in terms of money.
2. what i don't like about a yearly sub (totally personal reasons):
  * if there's a yearly sub i'm expecting way more admin people asking for refunds. so, need a proper refund policy. blah blah blah. boring admin stuff. i want to spend all (or at least most) of my time developing features for my apps, and for users. i DO spend time responding, answering, guiding, etc. but more "corporate" stuff etc.: not for me.
  * for a yearly sub discounted, then there's really no advantage for me, and again that will impact the users down the line. that'd mean for me same amount of money, but way more time wasted in dealing with refunds, admin stuff etc. so, less time to develop features properly. so ultimately, everybody ends up in a worse place at the end.

what i like about the monthly sub is that it doesn't tie people down. like if they find a better app, they can cancel their sub right away. worse case is they "lost" $3.28? they have the freedom to go for what they want. if an another app does a better job for them, please go use it. total support. life's too short to stick with bad stuff :D that also allows me to bring kV (and my other apps) wherever i want to. then again, if someone doesn't like the direction it takes, then they can stop subscribing right away. there's the case about an app recently, Homerow (i bought a lifetime license myself to support the dev). it worked in one way, then it totally changed. people paid $50 for a lifetime license, but the WHOLE APP changed. that mega sucks, i think. the dev of course has the right to do whatever he wants with his app, but that does suck for the users. with the monthly sub, you can cancel right away. don't like where the app is going? cancel. don't need it anymore? cancel. makes your day better? subscribe. i like this flexibility.

hope it makes sense.

question for you now: why do you want a yearly sub? what would be the advantages? also what would you expect? discount? thanks.

**Comment by javid-g** [comment]
Appreciate the detailed response, unrelated, but this is some good insight for me (i am a dev looking to spin up a few projects in my spare time).  I didn't even consider the additional admin work that annual subscriptions may result in.

I guess for me, I simply prefer paying for things annually and forgetting about them until the next annual payment where I can't even remember what I'm being charged for. You're right that this usually comes with a couple of free months or so, and that's a nice bonus. From marketing POV, I think it also pushes people over the edge if they see that discount offered for the yearly plan and are on the edge of subscribing or not (this is just anecdotal, what do I know lol). 

I have never found myself in a situation where I subscribed long term, and the product happened to take a completely different direction. I think if that happened I would be upset though. Hope that answers your question.

It's also kind of crazy the amount paddle charges on such a small subscription fee!!

**Comment by godbout** [comment]
> Appreciate the detailed response, unrelated, but this is some good insight for me (i am a dev looking to spin up a few projects in my spare time). I didn't even consider the additional admin work that annual subscriptions may result in.

my experience so far is that a few people cancel or stop paying after a few months. some come back. not sure exactly how this would translate for a yearly sub, but i'd still assume a couple of emails asking for a refund. quite a few end up subscribing again. tbh i track 0 of those things. no interest in the data. i just know specifically about the sub numbers because of the Paddle dashboard, and for the fun of it i update the site (kindavim.app) daily with the number of current subs. but that's about it. not looking forward to deal with more in that area 😂️

> I guess for me, I simply prefer paying for things annually and forgetting about them until the next annual payment where I can't even remember what I'm being charged for.

😂️ i never heard about that one before 🤣️🤣️🤣️
the kV's sub is recurring tho. if you subscribe once you're all set. just receiving an email monthly about your payment info but that's easily forwarded to the trash?

> From marketing POV, I think it also pushes people over the edge if they see that discount offered for the yearly plan and are on the edge of subscribing or not (this is just anecdotal, what do I know lol).

yeah, i don't want to "push" people over the edge. if i have to do this for them to subscribe, that means kV is probably not the right tool to start with, and they're not the subscribers i want. pushing them for 3.28 and month and then dealing with extra admin work? not worth it. i almost never hear about the current 80+ subscribers. and when i do, it's straight to the point, great useful feedback etc. what i hear a lot about is people complaining about the sub model. and when kV was open source, people who weren't able to compile 😂️

> Hope that answers your question.

it does. thank you! but i'll be honest, not good enough for me to add a yearly license sorry 😅️
some people mentioned about currency conversion from their bank that would add extra free. that was a good one.

> It's also kind of crazy the amount paddle charges on such a small subscription fee!!

that's on me, not Paddle. Paddle charges a 0.5$ fixed fee + 5% (i checked), whether you charge 1$ or 1000$. so it's just my price and model that sucks. but money is secondary. of course i would LOVE kV (and Wooshy) to pay for themselves. then i would be able to focus all my time on them without getting extra work or burning my savings, but that's secondary. priority is building stuff meaningful, that i need myself, learning along the process, and having a lot of fun. if i do that i win. money comes after. pricing will not change, it'll stay 3.28 (unless Paddle increases its fees). this is a long term game. i'm not building stuff for business reason, as far as i'm concerned this is self-expression/art. so yeah, it's long term. i use both apps daily, and they'll be maintained for as long as i use a Mac, which means as long as i use a computer, which means, with my lifestyle, as long as i'm alive. and i'm not planning to die before at least 88—47 more to go—and also, there's a setup for that when i die, even if suddenly, kV goes free and open source. ok, that was a lot of info 😅️

**Comment by godbout** [comment]
@javid-g Hepta doesn't have any free plan. requires almost 100US a year 😅️
as far as i can tell (from adding support to it in my other app Wooshy), this an Electron app. how is it working by default in kV? shouldn't be really good, right? most of the Electron apps don't bother implementing the macOS Accessibility. if it doesn't work well, add it to the `Electron` Family. thing is, i'm expecting it not to work well there either. the `Electron` Family is for Electron apps that implement the AX, but where there's some restrictions and you can't delete or change text. so usually the way to go is to add those Electron apps in the `Key Mapping` Family. as text is not readable, Vim motions have to be done through key remapping. not perfect, but most of the time it's enough to get the job done.

lemme know what you come up with, and then i'll add some text in kV's Wizard.

**Comment by javid-g** [comment]
Ah, I didn't realize they don't have a trial plan 😭 Fair enough, I have added it to the Key mapping and will check out how that behaves. As far as the subscription discussion goes, all of your points are fair. It's a cool perspective and fairly uncommon from what I have seen in the space. I will subscribe as monthly and keep an eye out if your stance on it changes for whatever reason.

Might be a silly question, but can I use a single license on two devices? (personal/business mac)

**Comment by godbout** [comment]
> Ah, I didn't realize they don't have a trial plan 😭

they said they're currently not enough people (3?) to handle free plans but it may come in the future. maybe you can support them by subscribing again 😂️

> Fair enough, I have added it to the Key mapping and will check out how that behaves. Before I had it in the Electron family and it would do some odd things when Im trying to focus. Like jumping all the way to the end instead of one line, etc.

yes, please lemme know. Electron apps are funky, because they do a lot of custom stuff. and very few care about Accessibility. there's a couples that do tho, like Logseq and some more that i don't remember. but most of the time it's hit-and-miss.

> As far as the subscription discussion goes, all of your points are fair. It's a cool perspective and fairly uncommon from what I have seen in the space. I will subscribe as monthly and keep an eye out if your stance on it changes for whatever reason.

🙏️
yes, it's definitely not common. i'm being told quite often that it's dumb. but it's so much fun 😂️
it may make the whole thing look less "professional", but i do daily personal support. i'm very reactive. i'm content, subscribers are content. win win to me.

> Might be a silly question, but can I use a single license on two devices? (personal/business mac)

yes. it follows the simplicity of what i do. there's no number of device limit etc. you just need a sub if you wanna use kV in the mornings. if you have a sub, please enjoy your life. you're "paying" for having a better time when you're on a computer, not for "a device", "or a year of update" etc. no headache. no extra thinking needed. that being said, Paddle informed me that some licenses were used like 50+ times 🤣️, so i think they've capped it to 6. but it's a soft limit. in case you need more, you let me know, i forward to them and they update on a per account basis. best probably though, in case you format a computer, or sell it etc., is to remove the License from the License pane in the Preferences. but if you forget or you don't, ultimately that will be fine too. i can handle from my side.

hope that helps!

**Comment by godbout** [comment]
added preliminary description in The Wizard in kV45: https://github.com/godbout/kindaVim.docs/releases/tag/45

**Comment by javid-g** [comment]
Hi again! Been liking kindaVim, though having some struggles in the context of this electron app 😬 
Sometimes when I enter the vim mode, my cursor jumps a line up. It only happens about half the time or so though. This is a tough ask but anything I can do on my end to improve this or is it just a shortcoming that's inevitable for an electron app?

**Comment by godbout** [comment]
my guess is that you've added Hepta to the `Key Mapping` Family, as described in The Wizard. when in the `Key Mapping` Family, kV uses its `Keyboard Strategy` to do Vim motions. because there's no way to get access to the text to do proper calculations, it's a little bit funky sometimes yes, we can't get a 100% level of accuracy, unfortunately.

now with the Keyboard Strategy, when you're dealing with text, entering Normal Mode will bring you back one character before. this is to match the Vim's habits. my guess, again, is that the issue you're seeing is when you enter Normal Mode at a beginning of a line (or bullet point?). because kV will go back one character, the caret ends up on the previous line. and coz we can't calculate if we're at the beginning of a line, we can't do much about this ☹️

i guess one thing i could always add is an option to switch ON or OFF that `going back a character` when entering Normal Mode using the Keyboard Strategy. lemme know what you think.

**Comment by godbout** [comment]
added in kV47: https://github.com/godbout/kindaVim.docs/releases/tag/47

as far as i'm concerned for now Hepta has been added, so i'm gonna close this. please feel free to comment more and ping me here, i'll answer. if one day Hepta gives away free trials, we can open an issue again. thanks.
