### ISSUE TITLE
Get out of visual mode without losing highlighted text

### ISSUE THREAD

**Issue by ericauld** [godbout/kindaVim.docs#151]
I may be missing it, but is there an easy way to get out of visual mode while keeping the selection?

As a workaround, I could send a command such as cmmd + c (if I don't mind losing the contents of the clipboard).

My use case is for programs (such as Roam) which do auto-surrounding with delimiters of highlighted text. I can highlight the text in visual mode, get out of visual mode, and then press e.g. `(` to surround the text.

**Comment by godbout** [comment]
> I may be missing it, but is there an easy way to get out of visual mode while keeping the selection?

the philosophy of kV is to stick to Vim's habits. as far as my research went in Vim you can't leave Visual Mode and keep the selection intact. BUT because kV also integrates with macOS, you can somehow 😀️ with the `passthroughs`:

<img width="642" alt="Screenshot 2022-12-22 at 14 53 46" src="https://user-images.githubusercontent.com/121373/209080716-d4e05a93-248c-4c5c-b425-214635d042fa.png">

if you switch on the passthroughs, any key combination that will contain `option` and/or `command` will be let through to macOS, and your Visual Selection will be kept intact. this is useful for stuff like Alfred's Universal Actions where you act on pieces of text.

> My use case is for programs (such as Roam) which do auto-surrounding with delimiters of highlighted text. I can highlight the text in visual mode, get out of visual mode, and then press e.g. `(` to surround the text.

so what you should probably do is assign a key combination that contain `option` and/or `command` to your programs, and use the passthrough. that'd be the kV vanilla/integrated way to do it. there's probably other ways possible too, with tools like Hammerspoon and using kV's [Distributed Notifications](https://github.com/godbout/kindaVim.docs#apis). you can listen to kV's Mode change, and act accordingly on them:

https://user-images.githubusercontent.com/121373/209081632-95e89b8b-7bb3-4966-bd4a-72b9a4503788.mp4

lemme know if that helps and if i understood your question correctly.

**Comment by ericauld** [comment]
Thank you, yes, that does answer my question. I appreciate your help!

**Comment by godbout** [comment]
sure. the apps come with heavy support. i (try to) answer daily. mostly i'm abusing the AX APIs which are already pretty funky, so it's quite hard for even an experienced macOS user (i think) to understand what's going on sometimes, and why kV (and the other apps) works the way they do. so i'm always here to answer. please always feel free to shoot!
