### ISSUE TITLE
Ignore Neovide

### ISSUE THREAD

**Issue by LachlanGray** [godbout/kindaVim.docs#154]
I've been using kinda vim for a while and it's been great, but I'm trying out Neovide, and can't figure out how to tell kinda vim to ignore it.

The problem is that if it is brew-installed, it doesn't come as an app but as a binary, and the ignore list won't accept it.

Is there a workaround? thanks!

**Comment by godbout** [comment]
can you have a look at this? https://github.com/godbout/kindaVim.docs/issues/119

we solved something similar with Neovide and LunarVim some months ago. the thread is a bit long tho coz we were both drunk by the time we solved it.

i'll check again with only Neovide now.

**Comment by godbout** [comment]
i think you're gonna have other issues by installing just the binary because other apps (not just kV) may require a bundle ID to do their job. for example i can't bring Neovide in the foreground with some Alfred Workflow.

what you probably wanna do is install the Neovide cask, like recommended by Homebrew: https://formulae.brew.sh/cask/neovide

then in your zsh or whatever, just alias `neovide` to the binary that exists within `Neovide.app`. there's something similar being done in a video from #119. have a look and lemme know.

**Comment by LachlanGray** [comment]
I’ll try this out, thanks!

**Comment by godbout** [comment]
how is it working? can we close?

**Comment by godbout** [comment]
closing as no news. please reopen if you still have issue.
