### ISSUE TITLE
add Mattermost

### ISSUE THREAD

**Issue by EdSplendor** [godbout/kindaVim.docs#157]
I added Mattermost to Electron apps, but it is still not working properly. For instance, delete word (dw) is not working

**Comment by godbout** [comment]
will check. what exactly is the behavior with `dw`? never works? doesn't work at the end of a text?

**Comment by godbout** [comment]
so first thing, Mattermost is an Electron app, but doesn't handle the macOS Accessibility well. very few Electron apps actually put the effort. you can see it in this video:

https://user-images.githubusercontent.com/121373/213842351-96a497b1-3eac-4d0c-ac71-9effc249d4c1.mp4

when you're on the first two characters, the Accessibility kicks in and kV can generate the block cursor. but as soon as you go further, it's gone. it's because Mattermost sends wrong data (it mixes line numbers with text lengths, etc.) so the Accessibility data is not usable.

in that case, Mattermost will have to go to the Key Mapping family. in there, Vim motions are "simulated" through key remapping. it's not as accurate as with text manipulation, that happens when the Accessibility data is correct, and when we can pinpoint exactly how the text should change.

second comment coming regarding the `dw` issue you'll currently find with the Key Mapping Family.

**Comment by godbout** [comment]
so this is the issue that you're gonna see currently with the `dw` move with the Key Mapping Family:

https://user-images.githubusercontent.com/121373/213842840-3e3c903f-4059-42cd-b687-89f8f3d7988b.mp4

it will work expect when you're on the last word of a text. the reason is that currently `dw` is translated to `option shift right; option shift right, option shift left; command c; delete`. that is to match Vim `dw`, and it works well UNLESS you're on the last word. i'm not sure yet if it's better to make `dw` behave like `cw` (except of course not returning to Insert Mode). that would help with the last word, but it wouldn't match the real Vim's `dw` in all the other cases.

still open to suggestions.

**Comment by godbout** [comment]
added in v48: https://github.com/godbout/kindaVim.docs/releases/tag/48
