### ISSUE TITLE
Use key combo to return to normal mode

### ISSUE THREAD

**Issue by lougreenwood** [godbout/kindaVim.docs#161]
I currently have `<c-[>` key combo to initiate `normal` mode. This is a default vim key combo.

However, I noticed that when in `visual` mode, I can't use this key combo to return to normal mode - I need to use `esc` instead. The `<c-[>` key combo works in vim to go from `visual` to `normal` mode.

Internally, is it possible for Kindavim to use the user-defined key combo as a general "mapping" to return to normal mode from other modes too?

**Comment by godbout** [comment]
yes, the hotkey to leave `Visual Mode` or to go back to `Insert Mode` has been asked several times. the reason i never did it was deliberate: because this is not Vim standard. and i don't want kV to promote bad habits when not necessary.

now it seems your case is a bit different? here's what the Vim doc says:

<img width="785" alt="Screenshot 2023-02-14 at 18 48 37" src="https://user-images.githubusercontent.com/121373/218714362-2c536387-9f93-4d80-808b-81a74b07f334.png">

to go back from `Visual Mode` to `Normal Mode`, the keys are `esc`, `v`, `V`, or `CTRL-V`, or _a non movement command that gets executed_. so i'm wondering, maybe your `CTRL-[` is a non movement command?

in Vim there's definitely a delay when you use `CTRL-[` before Vim goes back to `Normal Mode`, would that be that the command failed?

thinking out loud. coz still not sure i wanna implement this.

**Comment by lougreenwood** [comment]
Here's what the docs say for `:help CTRL-[` for me, if I read this correctly, it seems  that `c-[` is actually an alias for `esc`?

![Screenshot 2023-02-14 at 13 11 56](https://user-images.githubusercontent.com/12051736/218748945-e22d2220-a56a-40f7-bc0f-fa220a3f448c.png)

> in Vim there's definitely a delay when you use CTRL-[ before Vim goes back to Normal Mode, would that be that the command failed?

I don't see any delay, although I'm using `neovim` (0.8.latest)

**Comment by godbout** [comment]
> Here's what the docs say for `:help CTRL-[`. If I read this correctly, it seems that `c-[` is actually an alias for `esc`?

HA! yes, you seem to be right. great. then the whole thing makes sense. i just have to add the `CTRL-[` motion (and actually `esc`, not defined yet in the docs it seems). then the fact that you'll use `CTRL-[` to enter `Normal Mode` under macOS will somehow just be a coincidence.

> I don't see any delay, although I'm using `neovim` (0.8.latest)

you're right. i can confirm.

ok thanks then. seems everything is clear now. will implement!

**Comment by lougreenwood** [comment]
Beautiful - thank you!

**Comment by godbout** [comment]
coming in kV49. for both Accessibility and Keyboard Strategies.

https://user-images.githubusercontent.com/121373/219308327-cc21417e-7f18-406f-9ee1-4d98c2e7419a.mp4

**Comment by godbout** [comment]
added in kV49: https://github.com/godbout/kindaVim.docs/releases/tag/49
