### ISSUE TITLE
Command line (but not for "commands", per-se)

### ISSUE THREAD

**Issue by lougreenwood** [godbout/kindaVim.docs#162]
When using search forwards or backwards (`/` / `?`) I miss having a visual indication of what string I'm searching for. This pain is amplified by not highlighting the search matches as I type them. If I make a typo I don't know if there was no result or if I did a typo at all.

One solution could be to show a "command line" next to the mode indicator when performing these kind of operations.

It might look like something like this:

- Enter normal mode
- enter `/`
- See a "command line" pop up which contains the text `/` (and a pseudo blinking cursor for UX purposes?)
- continue to type my search term (`/something`)
- see that the command line now displays `/something` (maybe with pseudo blinking cursor for US purposes?)

**Note:** I'm not suggesting to add full support for proper vim commands (`:`), but rather to show something like the command line and emulate it's behaviour for the vim operations which are supported by KindaVim so that the user gets better feedback.

**Comment by godbout** [comment]
> This pain is amplified by not highlighting the search matches as I type them.

if i'm not wrong, related to this issue: https://github.com/godbout/kindaVim.docs/issues/120

> One solution could be to show a "command line" next to the mode indicator when performing these kind of operations.

ah. i see. you're using the `Vim Mode` for the Characters Window. coz in `Vim Move`, you'll see the search term.

https://user-images.githubusercontent.com/121373/218716957-66092f68-5cb4-4474-95f8-a4c5e551bb90.mp4

so, would adding this to the `Vim Mode` would be enough?

i'm skipping the rest because handling the cursor better is a massive endeavor. currently i'm faking it by using macOS' native way of drawing the cursor. but making your own AND hiding the native selection on apps/buffers that you don't own is another universe (and not even sure it's possible tbh). the rest of your comment is a too big thing sorry (new popup, etc.).

**Comment by lougreenwood** [comment]
I guess so, I didn't even know that there were 2 modes or remember choosing `Vim mode`. Maybe I should go read the docs too 😆

**Comment by godbout** [comment]
> I guess so, I didn't even know that there were 2 modes or remember choosing `Vim mode`. Maybe I should go read the docs too 😆

pretty sure default is `Vim Move` 😅️

**Comment by godbout** [comment]
coming in kV49:


https://user-images.githubusercontent.com/121373/219307273-5a585f30-e627-43dc-8f7f-e5428ca70264.mp4

**Comment by godbout** [comment]
works also for the `?` of course.

**Comment by godbout** [comment]
done in kV49: https://github.com/godbout/kindaVim.docs/releases/tag/49
