### ISSUE TITLE
Shared UI popover for KindaVim & Whooshy?

### ISSUE THREAD

**Issue by lougreenwood** [godbout/kindaVim.docs#163]
Did you consider having a shared UI component which is used by both KindaVim & Wooshy (I don't think Scrolla shows any popover?) to display their popovers/inputs?

Most of the time I want both of the apps to render their UI popovers in the same place, with the same styling etc from the same config.

Having a single place to configure how a user's "vim-like features provided by your apps" UI stuff is displayed could be a nice UX improvement.

If something like https://github.com/godbout/kindaVim.docs/issues/162 were to be implemented I could even see this being the same input which is used by Wooshy.

Maybe this `popover` could be a separate app (let's call its "godbout's god-mode popover" 😉) which both kinda vim populate (this would allow for a single config for the popover styling / positioning).

Alternatively, this abstraction pattern could open the door to a plugin pattern which would allow us to write plugins to instead use some universal app (like `Raycast` / `Alfred` etc) to handle this part of workflow and get even more consistency.

Just some food for thought 😄

**Comment by godbout** [comment]
hmm. a couple of thoughts.

i had/have the idea of something similar as the Characters Window for Wooshy's Non-Stealing Focus Mode. because not to steal focus, you can't have a text input. but that's again another universe (the whole key event system has to be different, rewriting macOS mappings, etc. 😴️). but nothing like a shared UI no. tbh the apps are already complicated, even definitely more kV. the `Display Engine` used tho is the same for kV and Wooshy. but not the UI. and i think, too complicated.

also, i've had some contacts about pushing kV like an big thing a la Raycast, but personally i'm really not interested 😂️ i wanna do code, on my own time, on my own terms. i like the fact that they are separate apps, and me making a lot of decisions so that the users don't have to. might not be the smartest choice (however you look at it), but i'm ok with it for now.

anyways, first thoughts. while having a beer. so yeah, we'll come back to that.

**Comment by godbout** [comment]
closing as this is not gonna be done.
