### ISSUE TITLE
Stopped working in CotEditor

### ISSUE THREAD

**Issue by bgoosmanviz** [godbout/kindaVim.docs#169]
Any tips? It used to work. Using "Esc" to enter normal mode. Do I need to restart my computer?

**Comment by godbout** [comment]
working nicely here with latest version 4.5.2.

did kV stop working only for CotEditor or for any other app? there's a bug in macOS where it stops sending keystrokes to apps that are registered. that affects kV and other apps that use the same system, like for example Alfred to expand snippets. restarting fixes the issue yeah. it happens three times for me in the past 2.5 years.

**Comment by bgoosmanviz** [comment]
Sorry for wasting your time; I restarted my computer and now it's working again 🤷

**Comment by godbout** [comment]
no worries. it's good to be reminded of this issue, because this needs to be reported to Apple. i hadn't done it yet because it only happened three times for me in three years so it's hard to find a pattern, and up until the last time i didn't know if it affected only kV. now i know it affects every apps that has an event tap. i'll report, link here, and close then issue only then.

**Comment by godbout** [comment]
https://github.com/feedback-assistant/reports/issues/390

**Comment by godbout** [comment]
(btw, CotEditor, very nice one!)
