### ISSUE TITLE
add Mellel 5

### ISSUE THREAD

**Issue by yuvalgavish** [godbout/kindaVim.docs#170]

**Comment by godbout** [comment]
will investigate. thanks.

**Comment by godbout** [comment]
i'll add it in the next version, that should come out beginning of May. first investigation makes it look like kV works out of the box with Mellel 5. are you seeing any issue?

**Comment by godbout** [comment]
testing more deeply now. seemed to work out of the box at the beginning, but some moves don't work, and some others even make kV crash. probably a Java app, with a non standard characters encoding. the macOS Accessibility returns UTF8 length strings. if the strings are not encoded properly then the counts returned are wrong, and calculation can't be made properly, and may crash kV it seems. will investigate more, but most probably Mellel 5 will only work with the Keyboard Strategy.

**Comment by godbout** [comment]
ok so same story as with Burp. see: https://github.com/godbout/kindaVim.docs/issues/82
Mellel 5 is a Java app. text encoding is not macOS standard (line linefeeds, etc.). been already taken care of when dealing with Burp but Mellel 5 also encodes characters that are not actually there, therefore making the macOS Accessibility return wrong data (string lengths, etc.) which makes kV crash.

the best, at least for now, is to add Mellel 5 to the Keyboard Strategy, so that the motions are done through key remapping. then i'll see how to avoid the crashes in kV. pretty sure Mellel 5 can't play nice with the macOS Accessibility tho. it's just completely non standard. always the issue with multi-platform apps.

**Comment by yuvalgavish** [comment]
Thank you very much

**Comment by godbout** [comment]
added in kV52: https://github.com/godbout/kindaVim.docs/releases/tag/52
