### ISSUE TITLE
Make docs more useful by linking to relevant vim docs

### ISSUE THREAD

**Issue by gordonbazeley** [godbout/kindaVim.docs#177]
* I love the app however my vim use is middling. 
* I'd like to extend my range of vim motions and moves.
* It would be easier for me to discover them if the KV docs gave a one line description of the move and a link to the relevant vim doc e.g. 
? - search backward for string - [? in pattern.txt](https://vimdoc.sourceforge.net/htmldoc/pattern.html#?)

What do you think please?

**Comment by godbout** [comment]
interesting. you're the second person in a few days with a similar issue. as you saw there's no "onboarding" or tutorial in kV. that's because kV is made for people who are already proficient with Vim, and just want their habits/muscle memory be _translated_ when using macOS. wanna go down the menu? `j` next email? `j`. down a line in your text? `j`. for tutorials and onboarding, there projects specialized for that, so it's definitely not kV's place.

that being said, linking kV's doc to the official Vim doc is a no brainer. will do that. adding a "summary" of what a move does in kV's doc, not sure yet. i wanna keep things simple, straight to the point. if the doc becomes too extensive, people will skip it. haven't decided yet if/what i'll do that with suggestion, but i keep it. will digest. thanks!

**Comment by joshuawagner** [comment]
I'm a noob to Vim but subscribed to this amazing software. I was def looking for some sort of link that would show me the keystrokes that I should memorize. Before I saw this issue, I assumed that it was roughly based on Vim but didn't realize that I could just go to the official Vim docs. Doing that now.

**Comment by godbout** [comment]
> I'm a noob to Vim but subscribed to this amazing software. 

that's bewildering to me 🤣️ the goal of kV was to allow people's _habits_ to be used everywhere on macOS. NOT to create the habits in the first place 😂️ surprised people use kV to "discover" Vim.

> I was def looking for some sort of link that would show me the keystrokes that I should memorize. Before I saw this issue, I assumed that it was roughly based on Vim but didn't realize that I could just go to the official Vim docs. Doing that now.

ultimately the goal of kV is to bring every Vim motion to the whole macOS. they're currently not all done. some also may not be doable due to limitations on the macOS APIs.

you can see the list of what's currently implemented in the README:
* Accessibility Strategy: https://github.com/godbout/kindaVim.docs/blob/master/AccessibilityStrategyImplementation.md#accessibility-strategy
* Keyboard Strategy: https://github.com/godbout/kindaVim.docs/blob/master/KeyboardStrategyImplementation.md#keyboard-strategy
* Commands: https://github.com/godbout/kindaVim.docs/blob/master/CommandsImplementation.md#commands

the difference between the Accessibility and the Keyboard Strategy is due to what data we can get from a field. native apps return all the necessary data (we need a lot) so that we can "calculate" how to manipulate text exactly. when a field doesn't return enough/proper data (mostly non native apps as they don't bother implementing Accessibility properly), we need to revert to trying to pretend a Vim motion through keyboard remapping. that's less precise, but no other way. in kV each Vim motions is therefore developed for different environments: Non Text Element, Text Element Accessible, Text Element Non Accessible.

**Comment by godbout** [comment]
btw if a move that you want is missing, just create an Issue to request it. then it'll become a priority on the list of move to develop.

**Comment by joshuawagner** [comment]
😆 sound good. Thanks for the explanation!

**Comment by godbout** [comment]
@gordonbazeley @joshuawagner i'm starting adding links to the Vim docs. see the first two moves here: https://github.com/godbout/kindaVim.docs/blob/master/AccessibilityStrategyImplementation.md

what do you think? useful? not? not worth it? my idea was to make all motions linked to the Vim docs. but without an extra "explanation" or "summary" of a motion. would that help or no?

**Comment by gordonbazeley** [comment]
Thanks for this @godbout - I like this and it will definitely be useful for me :-)

**Comment by godbout** [comment]
> Thanks for this @godbout - I like this and it will definitely be useful for me :-)

alright, good. thanks for letting me know. i'll link all the moves then 👍️

**Comment by godbout** [comment]
i'll be adding a bit every day coz it's very boring 😂️😂️😂️

**Comment by godbout** [comment]
ok so as usual, something that sounds easy will turn into another little rabbit hole. the Vim docs itself use uppercase/lowercase letters for their links. URL are case insensitive, so all uppercases will actually link to lowercases. this is not an issue with kV, this is an issue with the Vim docs itself. so i guess i'm gonna have to contact them and try to get this fixed on their side...

e.g.:
* https://vimdoc.sourceforge.net/htmldoc/change.html#P
* https://vimdoc.sourceforge.net/htmldoc/change.html#p

both will link to the lowercase `p` motion.

will contact them and update this thread accordingly.

**Comment by godbout** [comment]
Vim docs guy contacted regarding the uppercase/lowercase link issue. (through https://vimdoc.sourceforge.net/huh.php)

**Comment by godbout** [comment]
also opened a ticket: https://sourceforge.net/p/vimdoc/bugs/13/

**Comment by godbout** [comment]
so i think i've linked to most of the doc when possible. have a look: https://github.com/godbout/kindaVim.docs

i'll do a second pass soon but you can already point if there's errors or links missing. thanks.

**Comment by godbout** [comment]
no answer and second pass kinda done so closing.
