### ISSUE TITLE
add Canva

### ISSUE THREAD

**Issue by ProHaller** [godbout/kindaVim.docs#179]
So far, it doesn't seem like any binding worked. hjkl navigation would be nice. 

The Canva app is a graphic design platform that allows users to create visual content such as social media graphics, presentations, posters, flyers, and invitations. It offers a range of tools, templates, and stock images to make the design process easier and more accessible, even for those without design experience.

**Comment by godbout** [comment]
will check. new release should be coming soon. Canva should be included.

**Comment by godbout** [comment]
ok so i'm having a quick look and Canva is a massive Electron app. basically a browser where they're drawing the fuck they want. so it's gonna be REALLY HARD to get Vim motions to do what you _expect_ them to do. because what's the expectations? sometimes the motion is gonna switch slide, sometimes it's gonna go down menu, etc. too complex UI. i would combine kV with [Wooshy](https://github.com/godbout/Wooshy.docs) here in order to target UI Elements first, and then act on them with kV. 

see below:

https://github.com/godbout/kindaVim.docs/assets/121373/9b3a7c18-98b3-4de1-8431-88f9689404d4


https://github.com/godbout/kindaVim.docs/assets/121373/687b60ba-b011-417d-a17e-71185ba1d964

**Comment by godbout** [comment]
although i'll be honest, Wooshy seems to be slow with Canva. never been an issue till now, but i guess there's way too many UI Elements, and Electron is slow af originally already, even more once you activate the Accessibility. more investigation needed to see if there's something to be done on Wooshy's side.

**Comment by godbout** [comment]
added in kV52: https://github.com/godbout/kindaVim.docs/releases/tag/52

**Comment by ProHaller** [comment]
Damn man, that is some mighty reactivity. Thanks a lot.

**Comment by godbout** [comment]
LOL. usually stuff are added within days. used to be a release a week for years. but moved apartment, moved workstation. things took some time. but now settled for three years so we're back to the normal schedule. stuff are gonna 🚀️🚀️🚀️ from now on!
