### ISSUE TITLE
add Path Finder.app

### ISSUE THREAD

**Issue by onedrop2000** [godbout/kindaVim.docs#185]

**Comment by godbout** [comment]
will do. thanks.

**Comment by onedrop2000** [comment]
yeah man!

**Comment by godbout** [comment]
add in kV55: https://github.com/godbout/kindaVim.docs/releases/tag/55

**Comment by onedrop2000** [comment]
Hey,
Is there a way to get your app without subscription? I really would like to support your project, maybe the old fashioned way?

Thanks for your support.
Regards, Johannes

Onedrop Multimedia Agentur
Johannes Strickner
Pongartgasse 8, 6850 Dornbirn
Vorarlberg, Austria
T: +43 650 8220010
www.onedrop.co
Am 25. Juli 2023, 19:03 +0200 schrieb G. ***@***.***>:

**Comment by godbout** [comment]
> Hey, Is there a way to get your app without subscription? I really would like to support your project, maybe the old fashioned way? Thanks for your support. Regards, Johannes Onedrop Multimedia Agentur Johannes Strickner Pongartgasse 8, 6850 Dornbirn Vorarlberg, Austria T: +43 650 8220010 [www.onedrop.co](http://www.onedrop.co) Am 25. Juli 2023, 19:03 +0200 schrieb G. ***@***.***>:
> […](#)

ok, so what will come next may appear sarcastic BUT I SWEAR IT"S NOT. all 100% sincere.

a little bit of history first:
1. kV came out of my own need. i had no idea where i was going. it took 1.5 years of full-time research before being able to get something stable for myself, and realizing that it may interest other people. now it's gonna be about 3 years of work full-time. 
2. because of the nature of what's kV dealing with, it's constant work. every macOS upgrade breaks kV. i'm using Accessibility APIs to do something that it's not done for. also different apps have different levels of AX support, so i have to test and adapt for all of the ones that are supported. also because a lot of Electron apps don't give a fuck about Accessibility, they break BETWEEN VERSIONS. so it's not even apps that i need to support and test, but the same apps at different versions. so it's a lot of work.
3. 3.28US a month is really cheap. but i wanna keep it that way, and i've promised the earlier adopter that i'll never increase. i get emails for people telling me they'd be ready to pay 10 or 20US a month. they just don't want kV to disappear. 

now, if a sub is really a big issue for you, here's what i'd recommend:
1. use a "competitor". they're listed in the README here: https://github.com/godbout/kindaVim.docs#alternatives
2. hack/crack kV (or GitHub, then you could get the source)
3. build your own lol (ok that one is like 5% a joke)
4. maybe try to get around the sub with setting up your own configs in `Hammerspoon` and/or `Karabiner-Elements`

giving a one time payment price would just be suicidal for me. no price is worth the time and energy i'm spending on this. but if i could get enough money to not have to take shit jobs to pay the bill, that's all i'd be looking for. and a sub means constant support, both from me, and for the users. i like it that way.

good luck!
