### ISSUE TITLE
escape not registering

### ISSUE THREAD

**Issue by joshuawagner** [godbout/kindaVim.docs#187]
Hi, I'm wondering if I need to do some sort of reset because my escape keystroke is not registering with Mac OS, I think. For example, if I go to rename a file in finder, when I press escape nothing happens.

Using the Karabiner Elements event viewer I can see that the keystroke goes down and up again but nothing happens in Mac OS, even after uninstalling KindaVim (and restarting), just now.

When I still had KV installed and switched the 'return to normal mode' setting back to _escape_ and the override to _cmd+escape_, pressing escape would switch me out of "normal" mode (meaning out of KindaVim mode) but then when I pressed it the 2md time it still did nothing.

I think this whole thing started when I changed the setting in KindaVim that determines how to return override normal mode. I changed from double escape to a couple other options

Unfortunately there are a lot of other potential causes of the problem as well. I'll list them and maybe you can tell me what might be the culprit?

- **BetterTouchTool** (has keystroke based triggers, but none for escape)
- **Karabiner Elements** (I've been tweaking this around the same time, including changing my caps lock "alone" behavior to "escape" (which didn't work). To confirm that this wasn't conflicting I created a blank profile and the keys show up in the event viewer normally.
- **Mac OS Settings > keyboard > modifiers keys** (I messed with these for both the regular keyboard and the virtual keyboard by KarabinerE -- they're all back to their original settings now though, except that Caps is set to 'no action' in both Karabiner and hardware keyboard setups.
- **System preferences froze** while I was adding a keyboard shortcut. Had to force quit. Maybe a plist needs to be trashed?

Thanks,
Josh

**Comment by joshuawagner** [comment]
I ended up trashing a bunch of preferences in the library folder and that got things back to normal

**Comment by godbout** [comment]
do you know which plist you've removed?

kV's plist wouldn't do anything tbh. as long as kV is not running, the event tap wouldn't run and it wouldn't catch `escape` (or any other key).

there's a known bug in macOS where the event taps just stop working. this affects kV but also other apps that use event taps, like Alfred (snippets feature). i've reported it to Apple (https://github.com/feedback-assistant/reports/issues/390) but i think it's a long known issue and usually they don't care much coz just a restart solves the issue. but you mentioned you restarted, so, hmm, may probably have been something else yeah. anyways glad it works now, but i'd be surprised the issue came from kV.

**Comment by joshuawagner** [comment]
You're right, that wasn't the solution. I spoke too soon. I'm embarrassed
to say that I had a Keyboard Maestro macro swallowing the Escape key. 🤦
I also managed to get some good file corruption when that crash happened,
but First Aid in Recovery mode took care of that so I'm back to full-speed
now! Thanks!
Josh

**Comment by godbout** [comment]
HHAHAHHAAH that'll teach you for blaming kV HAHAHAHHAHAHHA
