### ISSUE TITLE
add QQ

### ISSUE THREAD

**Issue by Celve** [godbout/kindaVim.docs#230]

**Comment by godbout** [comment]
会加。谢谢你

**Comment by Celve** [comment]
This one: https://im.qq.com/index/

**Comment by godbout** [comment]
@Celve can you help? 😂️😂️😂️

![IMG_1034](https://github.com/godbout/kindaVim.docs/assets/121373/c44c56e0-98cb-42a1-a435-b27e02c3f581)

i used to have an account but i haven't been able to log in for ages because they've changed their system and it's a mess, especially if you're reading level of Simplified Chinese is lame. when i try the macOS app i need to scan a QR Code, so i guess i need to log in with my account, but need help. i tried to create a new account also but it requires me to SEND an SMS rather than receiving an OTP. i tried but i can't send. not sure if it's because i'm not in China. will be there on Thu but might be better if you can vouch for me with the QR Code above. 辛苦了

**Comment by Celve** [comment]
I would be more than glad to assist you. Unfortunately, it appears that the QR code has expired.

**Comment by godbout** [comment]
maybe best is you add me on WeChat and we do it live: ki_yom. thanks!

**Comment by godbout** [comment]
done in kV63: https://github.com/godbout/kindaVim.docs/releases/tag/63
