### ISSUE TITLE
add 有道云笔记

### ISSUE THREAD

**Issue by danny-su** [godbout/kindaVim.docs#244]
https://note.youdao.com/note-download

https://artifact.lx.netease.com/download/ynote-electron/%E6%9C%89%E9%81%93%E4%BA%91%E7%AC%94%E8%AE%B0-arm64.dmg

**Comment by godbout** [comment]
will check. thanks.

**Comment by godbout** [comment]
for the time being: seems the main note part is done with a bunch of StaticText... you need to put the app in the Key Mapping Family. but because the app itself reacts to some default macOS keyboard shortcuts, you'll get some weird UX. like the sidebar keeps hiding and showing up when you use `alt` lol, which is of course use for some remappings.
