### ISSUE TITLE
add Spark

### ISSUE THREAD

**Issue by LaP0573** [godbout/kindaVim.docs#92]
So far, I've noticed that:
- J and K are reversed, J goes up and K goes down in the emails list
- When going back and forth with H and L when composing an email, it doesn't move between letters, it first highlights the letter, then moves past it (so if your cursor is here : "anim|al" and you want to go before the m, if you press H once, it will highlight the m, and if you press it a second time only then it will move the cursor between i and m)

https://sparkmailapp.com/

**Comment by godbout** [comment]
cool, thanks for the report. will check this ASAP and if no mega edge cases, should be handled for kV27 (probably by the usual end of the week). keep you posted.

**Comment by godbout** [comment]
> * J and K are reversed, J goes up and K goes down in the emails list

with UI Elements what kV does is remap keys. `j` becomes `down`, `k` becomes `up`. so if the issue comes from kV it would be REALLY strange.

works fine here. but what i'm seeing is that there are different shortcut settings. some for Spark and some for Gmail. for those two settings, the `jk` moves are inverted. so i'm wondering, any chance you get the Gmail setting, and you were actually not in kV Normal Mode but just using the Spark shortcuts instead?

see video below:

https://user-images.githubusercontent.com/121373/176472775-5b017042-0dcc-4386-a9a2-a785b19850f3.mp4

**Comment by godbout** [comment]
> * When going back and forth with H and L when composing an email, it doesn't move between letters, it first highlights the letter, then moves past it (so if your cursor is here : "anim|al" and you want to go before the m, if you press H once, it will highlight the m, and if you press it a second time only then it will move the cursor between i and m)

here there are two issues:
1. they have some custom shit appearing when you select text. that breaks the selection etc calculations that kV needs to do. you can press somewhere down the composer to fix that toolbar rather than having it floating.
2. they're using a WebView for the composer, that is somehow restricted, so you can move but not delete or change text. this is what the `PG-R` Family is done for, in the Preferences. add Spark there, and then the text will be deleted/changed through other means.

see video below. i'm showing the issues and fixes in the order cited above. even with those 2 fixes though, there's still an issue with the character not being selected sometimes after a change/deletion. not sure why. i need to study more their implementation of the Accessibility. will do in the following days. worse case, you could put Spark in the `Key Mapping` Family. the Vim moves would be achieved through key remapping, so it's less precise and you don't have all the moves, but maybe that's enough to compose emails? up to you. let me know.

https://user-images.githubusercontent.com/121373/176474739-d908a2be-ae68-4059-858c-928d5c05ad84.mp4

**Comment by godbout** [comment]
seems you can't create new lines with the Accessibility. probably their stuff is returning wrong data. using the Keyboard Strategy is having issues with copying the deleted text to the clipboard too. seems their stuff is too custom. will check more in the following days.

**Comment by godbout** [comment]
i still need more time to check the macOS Accessibility with Spark. moving around works well but some changes/deletes move don't. need a bit more research first to make sure Spark is not workable with the Accessibility Strategy, and requires the Keyboard Strategy instead (Key Mapping or 911).

**Comment by godbout** [comment]
ok, so initial research:

1. Spark is one of those apps where you can't delete text with the Accessibility Strategy (Auto). so it needs to go to the `PG-R` Family
2. some moves will not work, like `O`, `o`, basically all the moves that insert linefeeds. this is because Spark doesn't handle pasting linefeeds properly, even without kV. see the video below. i will report this to them and see what they say.

https://user-images.githubusercontent.com/121373/178250529-8352577b-2a5c-44c1-8e10-9a231e8b880b.mp4

after reporting, i will research the Keyboard Strategy (`Key Mapping` and `911` Families). last time i checked grossly it seemed to have issues too. will comment again once done.

**Comment by godbout** [comment]
Spark was added in kV28: https://github.com/godbout/kindaVim.docs/releases/tag/28
ultimately i will go to the `PG-R` Family and will work very well with the Accessibility Strategy, once the Readdle team fixes the linefeed pasting issue. for the time being it goes to the Key Mapping. i will update once Readdle fixed.
