### ISSUE TITLE
add HEY

### ISSUE THREAD

**Issue by ajdubovoy** [godbout/kindaVim.docs#98]
When drafting emails, the commands don't work even with PG-R or Electron modes. If I push `j` it always goes to the bottom of the compose window, not the next line.

Anyway, VIM EVERYWHERE. Love it. Thanks for your work.

**Comment by godbout** [comment]
trying now. thank god they have 14 days trial. back to you soon.

**Comment by godbout** [comment]
ok so yes, Hey doesn't handle the macOS Accessibility properly, so we can't use the Accessibility Strategy (Auto, PG-R or Electron) to get the Vim motions. we'll have to use the Keyboard Strategy (Key Mapping, 911) that achieve Vim motions through key remapping. it's definitely less good, because we can't "calculate" and manipulate the text. but may be enough to compose an email?

add Hey to the Key Mapping Family:

![Screenshot 2022-07-22 at 17 58 41](https://user-images.githubusercontent.com/121373/180416111-d74daa7f-58de-4a11-8d79-275d5134048b.png)

i assume you haven't tried those because you weren't aware of them. that wouldn't be the first time. i may need to make this more clear. anyways, thanks for requesting Hey. will make kV better. i'm making a new release in a few hours, Hey will be added to The Wizard in that release.

**Comment by ajdubovoy** [comment]
Hi! Unfortunately, I already had it in there but it's still quite weird. For example, pushing `k` twice selects all the text instead of going up two lines. `j` always goes to the bottom. Anyway, it's their fault for not building a decent native implementation, definitely not yours!

**Comment by godbout** [comment]
> Hi! Unfortunately, I already had it in there but it's still quite weird. For example, pushing `k` twice selects all the text instead of going up two lines. `j` always goes to the bottom.

you have HEY in the Key Mapping? that's weird, because what you're describing is kinda typical of a faulty Accessibility implementation. is there any way that HEY is BOTH in PG-R/Electron, and in Key Mapping? (it shouldn't happen. it gets removed from a Family when you add it into another one. but who knows.)

here's the result i have here by adding HEY into the Key Mapping:

https://user-images.githubusercontent.com/121373/180419665-8e38f432-91a4-4a13-8c23-41967f080b12.mp4

**Comment by ajdubovoy** [comment]
<img width="722" alt="CleanShot 2022-07-22 at 12 28 41@2x" src="https://user-images.githubusercontent.com/39504104/180420581-4b5bc2e5-d788-4a59-b584-27d654952879.png">


Hm I deleted it and readded and it's still doing it for me. But who knows! Maybe after a restart it'll be fine

**Comment by godbout** [comment]
please see below:

https://user-images.githubusercontent.com/121373/180420646-1f038da3-6c62-4f1b-9fc0-da70d15eacae.mp4

also you may experience a crash if not added to Key Mapping. i see that HEY returns really corrupted data, like negative caret locations.

**Comment by ajdubovoy** [comment]
Oh wait no! I switched to keyboard strategy and now it's perfect. Thanks for your help!!!

**Comment by godbout** [comment]
> <img alt="CleanShot 2022-07-22 at 12 28 41@2x" width="722" src="https://user-images.githubusercontent.com/39504104/180420581-4b5bc2e5-d788-4a59-b584-27d654952879.png">
> 
> Hm I deleted it and readded and it's still doing it for me. But who knows! Maybe after a restart it'll be fine

you're still in the PG-R one. please check my pictures and videos. you need to add it to the `Key Mapping`. thanks.

**Comment by godbout** [comment]
> Oh wait no! I switched to keyboard strategy and now it's perfect. Thanks for your help!!!

ok good! definitely that Families Pane is not clear enough.

with Key Mapping the Vim moves are achieved through, well, key remapping. text can't be calculated and manipulated. so you can't have all the "kindaVim" motions.

here's the list of currently available moves for the Keyboard Strategy (Key Mapping, 911): https://github.com/godbout/kindaVim.docs/blob/master/KeyboardStrategyImplementation.md

enjoy.

**Comment by godbout** [comment]
HEY was added in kV29: https://github.com/godbout/kindaVim.docs/releases/tag/29
