### ISSUE TITLE
add Warp

### ISSUE THREAD

**Issue by haveanicedavid** [godbout/kindaVim.docs#99]
https://www.warp.dev

Warp doesn't have VI bindings, and because it's a proprietary editor even zsh / fish VI bindings won't work. 

FWIW, it seems like it's a [pretty requested feature](https://github.com/warpdotdev/warp/issues/159), so if kV worked in it, could be good marketing for you :D 

Love the project, thanks for your work 🙏

**Comment by godbout** [comment]
> https://www.warp.dev
> 
> Warp doesn't have VI bindings, and because it's a proprietary editor even zsh / fish VI bindings won't work.

wow. for a terminal that's rough. will make the first audit very soon. which means now.

> FWIW, it seems like it's a [pretty requested feature](https://github.com/warpdotdev/warp/issues/159), so if kV worked in it, could be good marketing for you :D

finally:
![donald-trump-billions](https://user-images.githubusercontent.com/121373/180595071-b2a58005-bc27-49f4-931b-2558c18186a6.gif)

**Comment by godbout** [comment]
**haveanicedavid** HAHHAHHAHHAHAH that's a very good one 🤣️

**Comment by godbout** [comment]
you can add Warp to the 911 Family:

https://user-images.githubusercontent.com/121373/180595336-cb2898ef-1a72-4e75-93cc-d5f92e548e03.mp4

the Vim moves are then done through key remapping, and kV considers any field as being a text field. that's because 911 is the last resort. Key Mapping doesn't work because for kV the input where you type text is not a text type (will need to investigate why) and the macOS Accessibility doesn't seem to be supported by Warp (at first glance, will have to investigate more too on that). will come back to you with more details later.

**Comment by godbout** [comment]
ok, so probably quickest investigation i've had to make. basically, Warp is not accessible at all. some apps return wrong info in their text fields/text areas (like almost any Electron), but Warp basically doesn't even do this. it's just a big Window. that's it. my guess is some sort of GPU rendering, maybe Metal, or some stuff like what is used by games. so nothing we can do except put it in 911, and get the Vim moves done through key remapping:

https://user-images.githubusercontent.com/121373/180595857-f9e5b853-6243-47a9-8d6c-871567fe9e08.mp4

**Comment by godbout** [comment]
ultimately this UX is gonna be bad with 911. see below:

https://user-images.githubusercontent.com/121373/180595933-a452a4e3-dce8-47cd-9c36-656b85f65a64.mp4

kV works on a per app basis. not per field, nor per process. if you add Warp to the 911 Family, kV takes over for the whole app. what happens when you use Vim within Warp? you're fucked.

so my advise: keep pushing the Warp team to get some Vim moves integrated natively, at least in the command line area. even if one day they implement the macOS Accessibility (doubt. if it's a GPU i don't even think they can.) kV will never be as good as the real Vim within it.

i'll add Warp to The Wizard for the next release, with a summary of what i'm talking above.

**Comment by haveanicedavid** [comment]
Ahh - that makes a lot of sense, thanks for the investigation and quick response

Back to Kitty I go, it seems. Thanks again! 

Ps can't wait for Wooshy

**Comment by godbout** [comment]
> Ahh - that makes a lot of sense, thanks for the investigation and quick response

my pleasure. makes kV better.

> Back to Kitty I go, it seems. Thanks again!

does kV work in Kitty? seems it's GPU rendered too (never tried).

> Ps can't wait for Wooshy

me too! been waiting for Paddle to approve my domains so that i can keep finishing the alpha. fingers crossed for next week. i want it out before i attack the next phase. i think it's already pretty usable so it'd be nice for people to have it in their hands!

**Comment by haveanicedavid** [comment]
Oh, I don't need it to - in kitty, fish + vi bindings works fine. It was really just warp that was causing issue

**Comment by godbout** [comment]
got it 👍️

**Comment by godbout** [comment]
FWIW, added in kV30: https://github.com/godbout/kindaVim.docs/releases/tag/30
